export const counselors = [
  {
    id: 1,
    name: "Dr. Sarah Ahmed",
    role: "Senior Education Counselor",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 2500,
    rating: 4.9,
    reviews: 195,
    experience: "8 years",
    successRate: "95%",
    students: 500,
    location: "Lahore, Pakistan",
    tags: ["Admissions", "Applications", "Interview Prep"],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    badge: "Top Rated",
    email: "dr.sarah.ahmed@counselor.pk",
  },
  {
    id: 2,
    name: "Prof. Muhammad Hassan",
    role: "Career Development Expert",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 3000,
    rating: 4.4,
    reviews: 203,
    experience: "12 years",
    successRate: "92%",
    students: 750,
    location: "Karachi, Pakistan",
    tags: ["Career Assessment", "Industry Insights", "Skill Development"],
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    badge: "Expert",
    email: "prof.hassan@counselor.pk",
  },
  {
    id: 3,
    name: "Prof. Aisha Khan",
    role: "Career Development Expert",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 2800,
    rating: 4.8,
    reviews: 203,
    experience: "10 years",
    successRate: "94%",
    students: 650,
    location: "Islamabad, Pakistan",
    tags: ["Career Guidance", "Interview Prep", "Skill Development"],
    image: "https://randomuser.me/api/portraits/women/67.jpg",
    badge: "Expert",
    email: "prof.aisha.khan@counselor.pk",
  },

  {
    id: 4,
    name: "Dr. Fatima Noor",
    role: "Senior Education Counselor",
    description:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    price: 2200,
    rating: 4.1,
    reviews: 195,
    experience: "6 years",
    successRate: "88%",
    students: 400,
    location: "Lahore, Pakistan",
    tags: ["Admissions", "Applications", "Career Guidance"],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    badge: "Top Rated",
    email: "dr.fatima.noor@counselor.pk",
  },
];
